default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sample_qmm3
  username: sample_qmm3_user
  password: JO7MPJGduC3kzs77kK6HJe6zTDowjb2s
  host: dpg-ckgmg9a12bvs73ft5h1g-a.oregon-postgres.render.com
  port: 5432

test:
  <<: *default
  database: sample_qmm3
  username: sample_qmm3_user
  password: JO7MPJGduC3kzs77kK6HJe6zTDowjb2s
  host: dpg-ckgmg9a12bvs73ft5h1g-a.oregon-postgres.render.com
  port: 5432

production:
  <<: *default
  database: sample_qmm3
  username: sample_qmm3_user
  password: JO7MPJGduC3kzs77kK6HJe6zTDowjb2s
  host: dpg-ckgmg9a12bvs73ft5h1g-a.oregon-postgres.render.com
  port: 5432
